# For ablation test



# Training Variables
run:
  num_envs: 512        # parallel envs (envs == num tracks)
  num_iterations: 1000 # upper bound training steps

# Running Environment Variables
env:
  seed: 67             # env RNG seed
  episode_length_s: 20 # max episode length (seconds)
  sim_dt: 0.02         # physics timestep (seconds)
  decimation: 10       # physics steps per policy step

# Terrain Layout Variables
terrain:
  # track sizes
  env_num_rows: 50
  env_num_cols: 50 

  # track pixel resolution
  row_spacing: 0.25
  col_spacing: 0.25
  color_sampling: false 
  car_width_m: 0.28 
  difficulty_range: [0, .9]
  phase_boundary: 0.0  # threshold for chains -> closed loops
  track_width_cells: 5 
  steps_per_segment: 40
  margin_frac: 0.1

# PPO Parameters
ppo:
  num_steps_per_env: 128              # rollout length before update
  max_iterations: 4000                # runner cap (overridden by run.num_iterations)
  save_interval: 50                   # save checkpoint interval
  experiment_name: "mushr_ppo_racing_mlp_vel" # ======= CHANGE THIS BETWEEN RUNS ========
  empirical_normalization: false      # For visual policies with proprio don't change
  algorithm:
    value_loss_coef: 3.0              # value loss weight in total loss
    use_clipped_value_loss: true      # PPO-style clipping on value loss
    clip_param: 0.2                   # PPO policy ratio clip
    entropy_coef: 0.01                # exploration bonus weight
    num_learning_epochs: 4            # gradient passes over each rollout
    num_mini_batches: 4               # mini-batches per epoch (inc for more freq updates)
    learning_rate: 5.0e-4             # optimizer step size
    schedule: "adaptive"              # learning rate to be dynamic
    gamma: 0.99                       # reward discount factor
    lam: 0.95                         # GAE smoothing factor
    desired_kl: 0.01                  # KL target for adaptive LR
    max_grad_norm: 1.0                # gradient-norm clip

# Actor Critic Policy Params
policy:
  class_name: "ActorCritic"
  init_noise_std: 1
  activation: "relu" # activation shared across ALL nn
  actor_hidden_dims: [64, 64]
  critic_hidden_dims: [64, 64]

  # Obs output is 60,80 with 20 top cropped
  image_shape: [1, 40, 80]
  cnn_channels: [16, 32]
  cnn_kernel_sizes: [5, 3]
  cnn_strides: [2, 2]
  cnn_out_dim: 64

  # Memory temporal encoder params
  rnn_type: "gru" # or `lstm`
  rnn_hidden_dim: 128 
  rnn_num_layers: 1

# Rewards (negative weights for penalties)
rewards:
  progress_rew_weight: 1.0
  time_step_pen_weight: -0.01
  goal_reached_rew_weight: 5.0 
  out_of_tile_pen_weight: -10.0

  # Old rewards kept for Ablation testing
  tangential_speed_weight: 1.5 
  cross_track_pen_weight: 0.3
  cross_track_k_in: 1.0      
  cross_track_k_out: 5.0 
  low_speed_thresh: 0.3 
  low_speed_weight: -0.2

# Goal Oriented Reward Parameters
goals:
  loop_dist_frac_range: [0.1, 0.95]
  off_track_wheel_threshold: 2
  goal_reached_eps_m: 0.5
  progress_clamp_m: 2.0


# Events -- these should generally go unchanged
events:
  wheel_friction:
    static_friction_range:  [0.4, 0.6]
    dynamic_friction_range: [0.4, 0.6]
    restitution_range:      [0.0, 0.0]
    num_buckets: 10
    make_consistent: false
  base_mass_range:  [1.0, 3.0]
  wheel_mass_range: [0.01, 0.3]
  spawn_yaw_offset_deg_range: [-30.0, 30.0]

# Observations
observations:
  enable_corruption: true
  concatenate_terms: true
  base_lin_vel_noise: [-0.1, 0.1]
  base_ang_vel_noise: [-0.1, 0.1]
  last_action_noise:  [-0.1, 0.1]
  last_action_clip:   [-1.0, 1.0]

# WandB Logging
logging:
  video: true
  video_length: 500
  video_interval: 15000       
  video_resolution: [1280, 720]
  video_crf: 30 
  log_every: 10
  checkpoint_every: 1000 
  no_checkpoints: false
  no_wandb: false
  wandb_project: "WheeledLab"
  no_log: false
  test_mode: false

  # Opt into recording videos of policy sensor 
  log_policy_camera: true 
  policy_camera_sensor_name: "camera" 
  policy_camera_env_id: 0
  policy_camera_fps: 5 # playback fps (5 = real-time at sim_dt*decimation = 0.2s)
